call plug#begin()
Plug 'liuchengxu/vista.vim'
Plug 'tpope/vim-fugitive'
Plug 'preservim/vim-markdown'
Plug 'machakann/vim-highlightedyank'
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()

colorscheme standard

set splitbelow splitright
set relativenumber laststatus=2 nowrap
set scrolloff=9999 hidden

set shiftwidth=4 smarttab expandtab
set tabstop=8 softtabstop=0
set directory=~/.config/vim/.swap undofile undodir=~/.config/vim/.undo

let g:vim_markdown_folding_disabled = 1
let g:vista_sidebar_width = 50
let g:vista_close_on_jump = 1
let g:vista#renderer#enable_icon = 0
let g:highlightedyank_highlight_duration = 300
let g:vamp_height = 10

nnoremap - :Vista!!<CR>
nnoremap gf :e <cfile><CR>
nnoremap <space>b :CtrlPMRU<CR>
nnoremap <space>e :CtrlP<CR>

autocmd FileType gitcommit,fugitive,fugitiveblame setlocal nonumber norelativenumber

let g:ctrlp_buffer_func = {
    \ 'enter': {-> execute('set laststatus=0')},
    \ 'exit': {-> execute('set laststatus=2')}
\ }
